#!/bin/bash
encode_rot13() {
   echo "$1" | tr 'A-Za-z' 'N-ZA-Mn-za-m'
}

decode_rot13() {
  echo "$1" | tr 'A-Za-z' 'N-ZA-Mn-za-m'
}

text="Hello, World"

encoded_text=$(encode_rot13 "$text")
decoded_text=$(decode_rot13 "$encoded_text")

echo "Original text: $text"
echo "Encoded text: $encoded_text"
echo "Decoded text: $decoded_text"
